version: '2'
services:
  persistence-app:
    image: persistence
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATA_MONGODB_URI=mongodb://persistence-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=persistence
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:29092
  signup-app:
    image: signup
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:29092
  persistence-mongodb:
    extends:
      file: mongodb.yml
      service: persistence-mongodb
  kafka:
    extends:
      file: kafka.yml
      service: kafka
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
